targets:
  qywx1:
    template: ./tmpls/default.js
    url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=qqqqqqqqqqqqqqqqqqqqqqqq
    type: weixin
  dingding1:
    url: https://oapi.dingtalk.com/robot/send?access_token=dddddddddddddddddddddddddddddddddd
    type: dingtalk
    secret: ssssssssssssssssssssssssssssssssss
ports: 8061
