targets:
  qywx1:
    template: ./tmpls/default.js
    url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ddddddddddddd
    type: weixin
  qywx2:
    url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=fffffffffffff
    type: weixin
ports: 8061
